- fix: \_be,\be_,\_rc_be,\_rc_b: directly defining return type to avoid error TS2742 - fix: \_be,\be_,\_rc_be,\_rc_b: \_val argument: return type set to Out - fix: \_be,\be_,\_rc_be,\_rc_b: Out extends NonNullable<unknown> = NonNullable<Ctx[Key]>: more flexible type - \_be,\be_,\_rc_be,\_rc_b: Out generic for return values - \_be,\be_,\_rc_be,\_rc_b: generic type is Ctx & keyof Ctx - fix: \_be,\be_: pending logic when key is not present in the ctx - \_be,\be_: ctx is required - fix: \be_: generic types - \_be,\be_: ctx is required - \_be,\be_: C generic type for ctx argument - fix: \_be,\be_: nondeterministic build issues - fix: \_be,\be_: typescript errors - fix: \_be,\be_: setting ctx[key] - fix: \_be,\be_ return value - fix: \_be,\be_: \_val(ctx, key, opts?): ctx & key are always passed - explicitly setting B types when \be_ is invoked - fix: \_be,\be_: allow unknown type